import { signIn } from "next-auth/react";
import Head from "next/head";
import AddApplicationForm from "~/components/AddApplicationForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home</h1>
        <button onClick={() => void signIn("", { callbackUrl: "/dashboard" })}>
          Sign In
        </button>
        <AddApplicationForm />
      </main>
    </>
  );
}
