import { signIn } from "next-auth/react";
import Head from "next/head";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto mt-20 max-w-5xl">
          <h1 className="text-center text-5xl font-semibold">
            Elevate Your Job Search
          </h1>
          <Button
            onClick={() => signIn("", { callbackUrl: "/home" })}
            variant="outline"
          >
            Get Started Now
          </Button>
        </div>
      </main>
    </>
  );
}
